# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('desc', models.CharField(default='1 Watch', max_length=255)),
                ('status', models.CharField(choices=[('DONE', 'Order Complete'), ('SHIPPED', 'Order Shipping'), ('CREATED', 'Order created, but not continued'), ('CRESHIP', 'Order created, Ship Address completed'), ('CRESHME', 'Order created, Ship method chosen'), ('CREPAID', 'Order Created, Payment Processed'), ('CHEKOUT', 'Order finalized, and order successfully placed.')], default='CHEKOUT', max_length=7)),
                ('payment', models.CharField(default='None', max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shipping_address', models.TextField(default='')),
                ('shipping_object', models.TextField(default='')),
                ('shipping_label', models.TextField(default='None')),
                ('shipping_tracking', models.TextField(default='None')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
                ('items', models.ManyToManyField(to='cart.Watch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DONE', 'Order Complete'), ('SHIPPED', 'Order Shipping'), ('CREATED', 'Order created, but not continued'), ('CRESHIP', 'Order created, Ship Address completed'), ('CRESHME', 'Order created, Ship method chosen'), ('CREPAID', 'Order Created, Payment Processed'), ('CHEKOUT', 'Order finalized, and order successfully placed.')], default='CREATED', max_length=7)),
                ('shipping_object', models.TextField(default=None, null=True)),
                ('payment', models.CharField(default='None', max_length=255, null=True)),
                ('cart', models.ManyToManyField(to='cart.ShoppingCart')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
