# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paintball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Mechanical designs by w^3')),
                ('on_hand', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('name', models.CharField(blank=True, default='Paintball Product', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255, null=True)),
                ('on_hand', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Mechanical designs by w^3')),
                ('on_hand', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('name', models.CharField(default='Watch Product', max_length=255)),
                ('images', models.ManyToManyField(blank=True, related_name='watch_image', to='cart.ProductImage')),
                ('parts', models.ManyToManyField(blank=True, related_name='watch_part', to='cart.ProductImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Watch'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paintball',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='paintball_image', to='cart.ProductImage'),
        ),
        migrations.AddField(
            model_name='paintball',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='paintball_part', to='cart.ProductImage'),
        ),
    ]
