# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Product', max_length=255)),
                ('description', models.TextField(default='Mechanical designs by w^3')),
                ('on_hand', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paintball',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.Category')),
            ],
            options={
                'verbose_name': 'Paintball Product',
            },
            bases=('cart.category',),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.Category')),
            ],
            options={
                'verbose_name': 'Watch Product',
            },
            bases=('cart.category',),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Category'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
